### ISSUE TITLE
ESPHome compile failing

### ISSUE THREAD

**Issue by tfcarlin** [screekworkshop/screek_light_sensor#2]
I'm receiving this when attempting to update the device. Is there a new yaml file I should be using?

```
INFO ESPHome 2023.9.2
INFO Reading configuration /config/esphome/luxsensor.yaml...
WARNING The selected Arduino framework version is not the recommended one. If there are connectivity or build issues please remove the manual version.
ERROR Unable to import component logger:
Traceback (most recent call last):
  File "/esphome/esphome/loader.py", line 165, in _lookup_module
    module = importlib.import_module(f"esphome.components.{domain}")
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/esphome/esphome/components/logger/__init__.py", line 28, in <module>
    from esphome.components.esp32.const import (
ImportError: cannot import name 'VARIANT_ESP32C2' from 'esphome.components.esp32.const' (/config/esphome/screek-components/esp32/const.py)
ERROR Unable to import component improv_serial:
Traceback (most recent call last):
  File "/esphome/esphome/loader.py", line 165, in _lookup_module
    module = importlib.import_module(f"esphome.components.{domain}")
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/esphome/esphome/components/improv_serial/__init__.py", line 1, in <module>
    from esphome.components.logger import USB_CDC, USB_SERIAL_JTAG
  File "/esphome/esphome/components/logger/__init__.py", line 28, in <module>
    from esphome.components.esp32.const import (
ImportError: cannot import name 'VARIANT_ESP32C2' from 'esphome.components.esp32.const' (/config/esphome/screek-components/esp32/const.py)
ERROR Unable to import component binary_sensor:
Traceback (most recent call last):
  File "/esphome/esphome/loader.py", line 165, in _lookup_module
    module = importlib.import_module(f"esphome.components.{domain}")
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/esphome/esphome/components/binary_sensor/__init__.py", line 7, in <module>
    from esphome.components import mqtt
  File "/esphome/esphome/components/mqtt/__init__.py", line 7, in <module>
    from esphome.components import logger
  File "/esphome/esphome/components/logger/__init__.py", line 28, in <module>
    from esphome.components.esp32.const import (
ImportError: cannot import name 'VARIANT_ESP32C2' from 'esphome.components.esp32.const' (/config/esphome/screek-components/esp32/const.py)
ERROR Unable to import component sensor:
Traceback (most recent call last):
  File "/esphome/esphome/loader.py", line 165, in _lookup_module
    module = importlib.import_module(f"esphome.components.{domain}")
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/esphome/esphome/components/sensor/__init__.py", line 6, in <module>
    from esphome.components import mqtt
  File "/esphome/esphome/components/mqtt/__init__.py", line 7, in <module>
    from esphome.components import logger
  File "/esphome/esphome/components/logger/__init__.py", line 28, in <module>
    from esphome.components.esp32.const import (
ImportError: cannot import name 'VARIANT_ESP32C2' from 'esphome.components.esp32.const' (/config/esphome/screek-components/esp32/const.py)
ERROR Unable to import component light:
Traceback (most recent call last):
  File "/esphome/esphome/loader.py", line 165, in _lookup_module
    module = importlib.import_module(f"esphome.components.{domain}")
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/esphome/esphome/components/light/__init__.py", line 4, in <module>
    from esphome.components import mqtt, power_supply
  File "/esphome/esphome/components/mqtt/__init__.py", line 7, in <module>
    from esphome.components import logger
  File "/esphome/esphome/components/logger/__init__.py", line 28, in <module>
    from esphome.components.esp32.const import (
ImportError: cannot import name 'VARIANT_ESP32C2' from 'esphome.components.esp32.const' (/config/esphome/screek-components/esp32/const.py)
ERROR Unable to import component button:
Traceback (most recent call last):
  File "/esphome/esphome/loader.py", line 165, in _lookup_module
    module = importlib.import_module(f"esphome.components.{domain}")
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/esphome/esphome/components/button/__init__.py", line 5, in <module>
    from esphome.components import mqtt
  File "/esphome/esphome/components/mqtt/__init__.py", line 7, in <module>
    from esphome.components import logger
  File "/esphome/esphome/components/logger/__init__.py", line 28, in <module>
    from esphome.components.esp32.const import (
ImportError: cannot import name 'VARIANT_ESP32C2' from 'esphome.components.esp32.const' (/config/esphome/screek-components/esp32/const.py)
WARNING The selected Arduino framework version is not the recommended one. If there are connectivity or build issues please remove the manual version.
Failed config

logger: [source /config/esphome/luxsensor.yaml:22]
  
  Component not found: logger.
improv_serial: [source /config/esphome/luxsensor.yaml:38]
  
  Component not found: improv_serial.
binary_sensor: [source /config/esphome/luxsensor.yaml:48]
  
  Component not found: binary_sensor.
  - platform: status
    name: Online
    id: ink_ha_connected
sensor: [source /config/esphome/luxsensor.yaml:53]
  
  Component not found: sensor.
  - platform: template
    id: sys_esp_temperature
    name: ESP Temperature
    lambda: return temperatureRead();
    unit_of_measurement: °C
    device_class: TEMPERATURE
    entity_category: diagnostic
  - platform: uptime
    name: Uptime
    id: sys_uptime
  - platform: wifi_signal
    name: RSSI
    id: wifi_signal_db
    entity_category: diagnostic
  - platform: template
    id: esp_memory
    icon: mdi:memory
    name: ESP Free Memory
    lambda: return heap_caps_get_free_size(MALLOC_CAP_INTERNAL) / 1024;
    unit_of_measurement: kB
    state_class: measurement
    entity_category: diagnostic
    disabled_by_default: True
  - platform: bh1750
    name: Illuminance
    filters: 
      - delta: 100.0
light: [source /config/esphome/luxsensor.yaml:87]
  
  Component not found: light.
  - platform: status_led
    name: sys_status
    pin: GPIO12
    internal: True
    restore_mode: ALWAYS_OFF
  - platform: status_led
    name: sys_status
    pin: GPIO13
    internal: True
    restore_mode: ALWAYS_OFF
button: [source /config/esphome/luxsensor.yaml:99]
  
  Component not found: button.
  - platform: restart
    icon: mdi:power-cycle
    name: ESP Reboot
  - platform: factory_reset
    disabled_by_default: True
    name: Factory Reset
    id: factory_reset_all
```

**Comment by screekworkshop** [comment]
From preliminary information, a large number of basic libraries seem to be nowhere to be found.  
If possible, try reinstalling esphome to see if that helps, and I'll take the time to investigate whether esphome 2023.9.2 might be causing the problem.  

Thanks.

**Comment by tfcarlin** [comment]
Any update? I've since upgraded to `ESPHome 2023.9.3`

**Comment by SLboat** [comment]
Family members have been in the hospital lately and it's been hard to carve out time to do some additional testing, I'm so sorry.  
I think it may take some additional time before I can do some relevant testing.

**Comment by tfcarlin** [comment]
Thanks for the update. The current fw is working fine so I'm all set for now.

**Comment by screekworkshop** [comment]
Hi, we've updated the dependency library and it's now compatible with 2023.10.  
I'm very sorry that it took so long.

**Comment by tfcarlin** [comment]
Still getting the same error. I tried "Clean Build Files" but that didn't make any difference. Thanks for the help!

**Comment by screekworkshop** [comment]
the new one will work for esphome 2023.10, here is my test:

https://github.com/screekworkshop/screek_light_sensor/assets/126383355/7199783a-d344-4e3f-9d70-8f8786e6a093

**Comment by tfcarlin** [comment]
OK, back in business. The new YAML works.
